# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

require 'cucumber/rails'
require 'capybara/poltergeist'
require 'capybara/cucumber'
require 'capybara-screenshot'
require 'capybara-screenshot/cucumber'
require 'rack_session_access/capybara'

ActionController::Base.allow_rescue = false
ActionController::Base.perform_caching = false
WebMock.allow_net_connect!
# Remove/comment out the lines below if your app doesn't have a database.
# For some databases (like MongoDB and CouchDB) you may need to use :truncation instead.
begin
  DatabaseCleaner.strategy = :truncation
rescue NameError
  raise 'You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it.'
end

Capybara.register_driver :poltergeist do |app|
  options = { js_errors: false, timeout: 30, phantomjs_logger: StringIO.new, logger: nil,
              phantomjs_options: ['--load-images=no', '--ignore-ssl-errors=yes',
                                  '--proxy-type=socks5', '--proxy=0.0.0.0:0',
                                  '--ssl-protocol=any']
            }

  Capybara::Poltergeist::Driver.new app, options
end

caps = Selenium::WebDriver::Remote::Capabilities.firefox({
    'tunnel-identifier' => ENV['TRAVIS_JOB_NUMBER']
})

sauce_driver = Selenium::WebDriver.for(:remote, {
  url: "http://#{ENV['SAUCE_USER_NAME']}:#{ENV['SAUCE_ACCESS_KEY']}@ondemand.saucelabs.com/wd/hub",
  desired_capabilities: caps
})

if ENV['SAUCE_LABS']
  Capybara.default_driver = sauce_driver
  Capybara.javascript_driver = sauce_driver

else
  Capybara.javascript_driver = :poltergeist
  Capybara.default_driver = :poltergeist
end

Capybara::Screenshot.prune_strategy = { keep: 30 }

Capybara.raise_server_errors = false

Capybara.default_selector = :css
Capybara.default_wait_time = 60

Before do
  Rails.cache.clear
  # page.driver.basic_authorize(Rails.configuration.basic_auth_user, Rails.configuration.basic_auth_pass) unless ENV['SAUCE_LABS']

  @cabinet_page ||= CabinetPage.new
  @login_page ||= LoginPage.new
end
