# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

require 'cucumber/rails'
require 'capybara/poltergeist'
require 'capybara/cucumber'
require 'capybara-screenshot'
require 'capybara-screenshot/cucumber'
require 'rack_session_access/capybara'

ActionController::Base.allow_rescue = false
WebMock.allow_net_connect!
# Remove/comment out the lines below if your app doesn't have a database.
# For some databases (like MongoDB and CouchDB) you may need to use :truncation instead.
begin
  DatabaseCleaner.strategy = :truncation
rescue NameError
  raise 'You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it.'
end

Capybara.register_driver :poltergeist do |app|
  options = { js_errors: true, timeout: 30, phantomjs_logger: StringIO.new, logger: nil,
              phantomjs_options: ['--load-images=no', '--ignore-ssl-errors=yes',
                                  '--proxy-type=socks5', '--proxy=0.0.0.0:0',
                                  '--ssl-protocol=any']
            }

  Capybara::Poltergeist::Driver.new app, options
end

Capybara::Screenshot.prune_strategy = { keep: 30 }
Capybara.javascript_driver = :poltergeist
Capybara.default_driver = :poltergeist

Capybara.raise_server_errors = false

Capybara.default_selector = :css
Capybara.default_wait_time = 15

Before do
  page.driver.basic_authorize(Rails.configuration.basic_auth_user,
                              Rails.configuration.basic_auth_pass)

  @home_page ||= HomePage.new
  @login_page ||= LoginPage.new
end
